separate predictor configs from targets
and standardize extract scripts between GCM/CPM and targets/predictors as much as possible

diff --git a/bin/moose/cpm/extract-day-target b/bin/moose/cpm/extract-day-target
--- a/bin/moose/cpm/extract-day-target
+++ b/bin/moose/cpm/extract-day-target
@@ -2,29 +2,58 @@
 
 set -euo pipefail
 
-domain=$1
-variable=$2
-ensemble_member=$3
-job_id=$4
-shift 4
+scenario="rcp85"
+scale_factor="4"
+frequency="day"
+collection="land-cpm"
+size=64
+
+job_id=0 # ID of job to depend on (0 means no dependency)
+
+while getopts ":d:v:e:j" opt; do
+  case ${opt} in
+    d)
+      domain=${OPTARG}
+      ;;
+    v)
+      variable=${OPTARG}
+      ;;
+    e)
+      ensemble_member=${OPTARG}
+      ;;
+    j)
+      job_id=${OPTARG}
+      ;;
+   \? )
+     echo "Invalid Option: -${OPTARG}" 1>&2
+     exit 1
+     ;;
+  esac
+done
+shift $((OPTIND -1))
+
 years=$@
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-scale_factor="4"
-target_resolution="2.2km-coarsened-4x"
-target_size=64
-frequency="day"
-variable="${SCRIPT_DIR}/../../../config/variables/${frequency}/land-cpm/${variable}.yml"
+variable_config_path="${SCRIPT_DIR}/../../../config/variables/${frequency}/${collection}/targets/${variable}.yml"
 
-QUEUE_DEP_PATH=${SCRIPT_DIR}/../queue-dep-func
-BATCH_WRAPPER_PATH=${SCRIPT_DIR}/../batch-wrapper
+QUEUE_LOTUS_PATH=${SCRIPT_DIR}/../queue-lotus
+LOTUS_WRAPPER_PATH=${SCRIPT_DIR}/../lotus-wrapper
 
 function queue_years {
   local job_id=$1
   shift 1;
   local years=$@
-  ${QUEUE_DEP_PATH} -j ${job_id} -d ${SCRIPT_DIR} -- ${BATCH_WRAPPER_PATH} --variable-config ${variable} --domain ${domain} --scale-factor ${scale_factor} --target-resolution ${target_resolution} --target-size ${target_size} --frequency ${frequency} --ensemble-member ${ensemble_member} ${years}
+
+  local args=()
+  args+=('--variable-config' ${variable_config_path})
+  args+=('--ensemble-member' ${ensemble_member})
+  args+=('--scenario' ${scenario})
+  args+=('--domain' ${domain})
+  args+=('--scale-factor' ${scale_factor})
+  args+=('--size' ${size})
+  ${QUEUE_LOTUS_PATH} -m 28G -j ${job_id} -d ${SCRIPT_DIR} -- ${LOTUS_WRAPPER_PATH} ${args[@]} ${years}
 }
 
 echo
