iterate over streams within moo-select
rather than parallelizing across them
to hopefully overload mass less

diff --git a/bin/moose/cpm/moo-select b/bin/moose/cpm/moo-select
--- a/bin/moose/cpm/moo-select
+++ b/bin/moose/cpm/moo-select
@@ -72,27 +72,30 @@ echo ${em} ${tp};
 
 mkdir -p ${output_dir}
 
-retries=2
-while true; do
-  set -x
-  time moo select -I ${SCRIPT_DIR}/${tp}/searchfile moose:crum/${suite_id}/${stream}.pp ${output_dir}
-  set +x
-  s=$?
+for stream in apa apb; do
+
+  retries=2
+  while true; do
+    set -x
+    time moo select -I ${SCRIPT_DIR}/${tp}/searchfile moose:crum/${suite_id}/${stream}.pp ${output_dir}
+    set +x
+    s=$?
+    if [ $s -eq 0 ] || [ $s -eq 17 ]; then
+      break;
+    fi
+    ((retries--));
+    if [ $retries -le 0 ]; then
+      break;
+    fi
+    echo "Retrying after a brief pause"
+    sleep 3;
+  done
+
   if [ $s -eq 0 ] || [ $s -eq 17 ]; then
-    break;
+    echo "DONE ${stream}: ${s}";
+  else
+    echo "FAILED ${stream}: {$s}"
   fi
-  ((retries--));
-  if [ $retries -le 0 ]; then
-    break;
-  fi
-  echo "Retrying after a brief pause"
-  sleep 3;
 done
 
-if [ $s -eq 0 ] || [ $s -eq 17 ]; then
-  echo "DONE";
-else
-  echo "FAILED: {$s}"
-fi
-
-exit $s
+echo "DONE"
