try extracting in portions of a year in moo-select

diff --git a/bin/moose/cpm/moo-select b/bin/moose/cpm/moo-select
--- a/bin/moose/cpm/moo-select
+++ b/bin/moose/cpm/moo-select
@@ -6,70 +6,93 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 for suite_id in "$@"; do
 
-case $suite_id in
-  mi-bb171|mi-bb190|mi-bb193|mi-bb196|mi-bb199|mi-bb202|mi-bb205|mi-bb209|mi-bb214|mi-bb217|mi-bb220|mi-bb223)
-    tp="1981-2000"
-    ;;
-  mi-bb188|mi-bb191|mi-bb194|mi-bb197|mi-bb200|mi-bb203|mi-bb206|mi-bb210|mi-bb215|mi-bb218|mi-bb221|mi-bb224)
-    tp="2021-2040"
-    ;;
-  mi-bb189|mi-bb192|mi-bb195|mi-bb198|mi-bb201|mi-bb204|mi-bb208|mi-bb211|mi-bb216|mi-bb219|mi-bb222|mi-bb225)
-    tp="2061-2080"
-    ;;
-  *)
-    echo "unknown suite id ${suite_id}"
-    exit 1
-    ;;
-esac
-
-echo ${suite_id} ${tp};
-
-for variable in psl mlqtw; do
-
-  case $variable in
-    psl)
-      stream="apa"
+  case $suite_id in
+    mi-bb171|mi-bb190|mi-bb193|mi-bb196|mi-bb199|mi-bb202|mi-bb205|mi-bb209|mi-bb214|mi-bb217|mi-bb220|mi-bb223)
+      tp="1981-2000"
+      years=$(seq 1981 2000)
       ;;
-    mlqtw)
-      stream="apb"
+    mi-bb188|mi-bb191|mi-bb194|mi-bb197|mi-bb200|mi-bb203|mi-bb206|mi-bb210|mi-bb215|mi-bb218|mi-bb221|mi-bb224)
+      tp="2021-2040"
+      years=$(seq 2021 2040)
+      ;;
+    mi-bb189|mi-bb192|mi-bb195|mi-bb198|mi-bb201|mi-bb204|mi-bb208|mi-bb211|mi-bb216|mi-bb219|mi-bb222|mi-bb225)
+      tp="2061-2080"
+      years=$(seq 2061 2080)
       ;;
     *)
-      echo "unknown variable ${variable}"
+      echo "unknown suite id ${suite_id}"
       exit 1
       ;;
   esac
 
-  output_dir="/gws/nopw/j04/furflex/henrya/projects/furflex/data/moose-experiments/1981-2000-pSTW-cpm/${suite_id}/${variable}/data"
-  mkdir -p ${output_dir}
+  echo ${suite_id} ${tp};
 
-  retries=2
-  while true; do
-    searchfile_path="${SCRIPT_DIR}/${tp}/${variable}/searchfile"
-    cp ${searchfile_path} ${output_dir}
-    set -x
-    time moo select -I ${searchfile_path} moose:crum/${suite_id}/${stream}.pp ${output_dir}
-    set +x
-    s=$?
-    if [ $s -eq 0 ] || [ $s -eq 17 ]; then
-      break;
-    fi
-    ((retries--));
-    if [ $retries -le 0 ]; then
-      break;
-    fi
-    echo "Retrying after a brief pause"
-    sleep 3;
+  for variable in psl mlqtw; do
+
+    case $variable in
+      psl)
+        stream="apa"
+        ;;
+      mlqtw)
+        stream="apb"
+        ;;
+      *)
+        echo "unknown variable ${variable}"
+        exit 1
+        ;;
+    esac
+
+    output_dir="/gws/nopw/j04/furflex/henrya/projects/furflex/data/moose-experiments/1981-2000-pSTW-cpm/${suite_id}/${variable}/data"
+    mkdir -p ${output_dir}
+
+
+    for year in ${years[@]}; do
+      echo "Processing ${suite_id} ${variable} ${year}"
+      searchfile_path="${SCRIPT_DIR}/${tp}/${variable}/searchfile"
+
+      case $variable in
+        psl)
+          cat > ${output_dir}/searchfile << EOF
+begin
+    stash=16222
+    T1>={${year}/12/01}
+    T1<{$((year-1))/12/01}
+end
+EOF
+          ;;
+        mlqtw)
+          cat > ${output_dir}/searchfile << EOF
+begin
+    stash=(30201, 30202, 30204, 30205)
+    lblev=(250, 500, 700, 850)
+    T1>={${year}/12/01}
+    T1<{$((year-1))/12/01}
+end
+EOF
+          ;;
+        *)
+          echo "unknown variable ${variable}"
+          exit 1
+          ;;
+      esac
+
+      cat ${output_dir}/searchfile
+
+      set -x
+      time moo select -I ${output_dir}/searchfile moose:crum/${suite_id}/${stream}.pp ${output_dir}
+      set +x
+
+      if [ $s -eq 0 ] || [ $s -eq 17 ]; then
+        echo "DONE ${stream} ${year}: ${s}";
+      else
+        echo "FAILED ${stream} ${year}: ${s}"
+      fi
+    done
+
+  echo "DONE ${suite_id} ${variable}"
   done
 
-  if [ $s -eq 0 ] || [ $s -eq 17 ]; then
-    echo "DONE ${stream}: ${s}";
-  else
-    echo "FAILED ${stream}: {$s}"
-  fi
-done
-
-echo "DONE ${suite_id}"
-
+  echo "DONE ${suite_id}"
 done
 
 echo "DONE"
